#!/usr/bin/expect -f

set DISK [lindex $argv 0];
set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout -1
spawn parted /dev/$DISK rm 2
match_max 100000
expect -exact "Yes/No? "
send -- "Yes\r"
expect -exact "Ignore/Cancel? "
send -- "Ignore\r"
expect eof
